services:
  web:
    build: .
    container_name: flask_web
    ports:
      - "5000:5000"
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: flask_redis
    ports:
      - "6379:6379"